tests:
	python -m unittest discover test -b

coverage:
	coverage run --source=nnhelper -m unittest discover -s test -p "test_*.py" -b
	coverage html --skip-covered
	open htmlcov/index.html

install_python:
	pip install -r requirements.txt